name: PHP Create release asset

on:
  push:
    tags: ["**"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get tag
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get release
      id: release
      uses: joutvhu/get-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.output.tag }}
  
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
  
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create release asset
      run: mkdir /tmp/fachbetrieb && cp -r * /tmp/fachbetrieb && cd /tmp && zip -r fachbetrieb-${{ steps.tag.outputs.tag }}.zip fachbetrieb

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: /tmp/fachbetrieb-${{ steps.tag.outputs.tag }}.zip
        asset_name: fachbetrieb-${{ steps.tag.outputs.tag }}.zip
        asset_content_type: application/zip

